### ISSUE TITLE
Callback not firing

### ISSUE THREAD

**Issue by jiiis** [alleyinteractive/webpack-git-hash#6]
Hi @joshkadis Good job on creating this very useful plugin.

Just there seems to be a small issue with invoking the callback.

The following code is being used

``` js
compiler.plugin('done', this.doCallback);
```

While in the definition of `WebpackGitHash.prototype.doCallback`, the `this` keyword was used. This results in `this` referencing the `compiler` object but not the plugin instance.

**Comment by joshkadis** [comment]
Thanks! Good catch, I overlooked the context for `doCallback()` when not cleaning up obsolete bundles/chunks. Will get a fix together shortly.

**Comment by joshkadis** [comment]
See version `1.0.2`, thanks again!
